<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="cleartype" content="on">

  <title><%= slugName %></title>

  <meta name="viewport" content="width=device-width">

  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">

  <!-- build:css styles/main.css -->
  <!-- bower:css -->
  <link rel="stylesheet" href="bower_components/normalize-css/normalize.css" />
  <!-- endbower -->
  <link rel="stylesheet" href="styles/main.css" />
  <!-- endbuild -->

  <script src="bower_components/modernizr/modernizr.js"></script>
</head>
<body>
  <!--[if lt IE 8]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->

  <header id="header" class="container">
    <h1 id="logo"><a href="/"><img src=""></a></h1>

    <nav>
      <ul id="main-nav">
        <li><a href="index.html">Index</a></li>
        <li><a href="content.html">Content</a></li>
      </ul>
    </nav>
  </header>
